### ISSUE TITLE
Favicon can get really big

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-customize-pane-resizer#1]
<img width="1319" alt="screen shot 2015-12-03 at 6 04 28 pm" src="https://cloud.githubusercontent.com/assets/2846578/11576951/56ae3692-99e8-11e5-94bf-bd3d59991564.png">

<img width="1319" alt="screen shot 2015-12-03 at 6 05 37 pm" src="https://cloud.githubusercontent.com/assets/2846578/11576976/7b360cba-99e8-11e5-8c5d-618642d56d9e.png">

We should consider adding a max-width on the favicon image (and probably the buttons underneath it) so it doesn't distort too much.

**Comment by jtsternberg** [comment]
Addressed here: https://github.com/xwp/wp-customize-pane-resizer/pull/9
