### ISSUE TITLE
Remember the user's pane width preference

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-pane-resizer#5]
If I drag the resizer to make the pane twice as big, and then I reload the Customizer, the pane width should restore to the previously-selected width. It could store the user's pane width preference in `localStorage`.

**Comment by jtsternberg** [comment]
Cool, do we have any WP core precendence using `localStorage`? And @scottopolis mentions using `sessionStorage` instead, so it will reset after a session, which could be good to 'reset' to the default occasionally.

**Comment by jtsternberg** [comment]
I found some precedence for `sessionStorage` in `wp-includes/js/autosave.js`.

**Comment by westonruter** [comment]
OK, good point.

**Comment by jtsternberg** [comment]
This will be closed when merging https://github.com/xwp/wp-customize-pane-resizer/pull/8

**Comment by westonruter** [comment]
PR merged.
