### ISSUE TITLE
Does not work 😡

### ISSUE THREAD

**Issue by grappler** [xwp/wp-customize-pane-resizer#6]
Hey,

I am not sure what I did wrong but I cannot resize the customizer on my test site.

I am running WP 4.4-RC1-35761 on PHP 7 using Twenty Sixteen.

Checking the console I only have a warning "RESIZER-JS" but no JS errors.

The HTML `<div class="customizer-resizer"></div>` does get added to the markup so something is working.

**Comment by jtsternberg** [comment]
@grappler oops! Forgot to update the minified version. Should be good now (or enable SCRIPT_DEBUG).

**Comment by grappler** [comment]
Thanks, it is working now :smile:
